import localFont from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"


export const metadata = {
  title: "AI Room Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
